### ISSUE TITLE
Pipeline fail at READ_YAML

### ISSUE THREAD

**Issue by cintiaoi** [sanger-tol/genomeassembly#68]
Hi,
I cloned the last version of genome assembly. But I'm having this issue in the first step read_yaml
This step was not there before. I don't know what's wrong. 
This is the error:

```
Cannot get property 'long_reads' on null object -- Check script './subworkflows/local/utils_nfcore_genomeassembly_pipeline/../../../modules/local/read_yaml/main.nf' at line: 67
```

my yaml looks like this:

```
dataset:
  id: trypoxyllum
  pacbio:
    reads:
      - reads: /home/cakemioi/projects/nhm/cake/trypoxyllum/XDOVE_20230807_R84050_PL100300828-2_C01_bc2044-bc2044.hifi_reads.fastq.gz
  HiC:
    reads:
      - reads: /home/cakemioi/projects/nhm/cake//trypoxyllum/XDTG_OmniC_852.sorted.cram
hic_motif: GATC,GANTC,CTNAG,TTAA
busco:
  lineage: hymenoptera_odb10
```
